name: Run DotNet examples

on:
  schedule:
    - cron: '35 22 * * *'
  workflow_dispatch:
  pull_request:
    branches:
      - trunk
    paths:
      - 'examples/dotnet/**'
  push:
    branches:
      - trunk
    paths:
      - 'examples/dotnet/**'

env:
  DISPLAY: :99
  GITHUB_TOKEN: ${{ secrets.SELENIUM_CI_TOKEN }}
  GH_TOKEN: ${{ secrets.SELENIUM_CI_TOKEN }}

jobs:
  test_examples:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout GitHub repo
      uses: actions/checkout@v3
    - name: Start Xvfb
      if: matrix.os == 'ubuntu-latest'
      run: Xvfb :99 &
    - name: Set up .Net
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Run tests
      uses: nick-invision/retry@v2.8.3
      with:
        timeout_minutes: 20
        max_attempts: 3
        command: |
          cd examples/dotnet/SeleniumDocs
          dotnet test
